allprojects {
    group = 'dbms'
    version = '0.1.0-SNAPSHOT'
}

subprojects {
    apply plugin: 'java-library'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    repositories {
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.compilerArgs += ['-Xlint:all', '-Werror']
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
        testLogging {
            events 'passed', 'failed', 'skipped'
            showExceptions = true
            showCauses = true
            showStackTraces = true
            exceptionFormat = 'full'
        }
    }
}
